version: '3.8'

services:
  discovery:
    build:
      context: ./
      dockerfile: ./discovery-service/Dockerfile
    ports:
      - '8761:8761'
    environment:
      - server_port=8761
    networks:
      - car-rental

  config:
    build:
      context: ./
      dockerfile: ./config-service/Dockerfile
    ports:
      - '8888:8888'
    environment:
      - server_port=8888
      - config_server_default_branch=main
      - config_server_git_uri=https://github.com/mohammed-mostakim-ornob/car-rental-config
    networks:
      - car-rental

  car:
    build:
      context: ./
      dockerfile: ./car-service/Dockerfile
    ports:
      - '8100:8100'
    environment:
      - server_port=8100
      - config_server=http://config:8888
      - eureka_default_zone=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    links:
      - discovery
      - config
    restart: on-failure
    networks:
      - car-rental

  location:
    build:
      context: ./
      dockerfile: ./location-service/Dockerfile
    ports:
      - '8200:8200'
    environment:
      - server_port=8200
      - config_server=http://config:8888
      - eureka_default_zone=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    links:
      - discovery
      - config
    restart: on-failure
    networks:
      - car-rental

  rent:
    build:
      context: ./
      dockerfile: ./rent-service/Dockerfile
    ports:
      - '8300:8300'
    environment:
      - server_port=8300
      - config_server=http://config:8888
      - eureka_default_zone=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
      - car
      - location
    links:
      - discovery
      - config
      - car
      - location
    restart: on-failure
    networks:
      - car-rental

  api-gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - server_port=8000
      - config_server=http://config:8888
      - eureka_default_zone=http://discovery:8761/eureka
    depends_on:
      - car
      - location
      - rent
    links:
      - car
      - location
      - rent
    restart: on-failure
    networks:
      - car-rental

networks:
  car-rental: