CREATE TABLE IF NOT EXISTS manufacturer
(
    name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS car
(
    code VARCHAR(255) NOT NULL PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    rent_per_kilo DOUBLE PRECISION NOT NULL,
    manufacturer_name VARCHAR(255) NOT NULL REFERENCES manufacturer(name)
);